azs:
- name: us1
  cloud_properties: {zone: ((zone))}

vm_types:
# Used by Concourse ATC and TSA VM
- name: concourse_cpi
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
      - ((concourse_atc_tag))
      - ((nat_traffic_tag))
    target_pool: ((concourse_target_pool))
# Used by Concourse database VM
- name: concourse_cpi_database
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
      - ((concourse_db_tag))
      - ((nat_traffic_tag))
# Concourse Worker vm types
- name: concourse_worker_8_16
  cloud_properties:
    cpu: 8
    ram: 16_384
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((concourse_worker_tag))
- name: concourse_worker_8_20
  cloud_properties:
    cpu: 8
    ram: 20_480
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((concourse_worker_tag))
- name: concourse_worker_8_24
  cloud_properties:
    cpu: 8
    ram: 24_576
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((concourse_worker_tag))
- name: concourse_worker_4_16
  cloud_properties:
    cpu: 4
    ram: 16_384
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((concourse_worker_tag))
- name: concourse_worker_4_8
  cloud_properties:
    cpu: 4
    ram: 8_192
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((concourse_worker_tag))
- name: concourse_worker_2_8
  cloud_properties:
    cpu: 2
    ram: 8_192
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((concourse_worker_tag))
# Used by OpenVPN Server
- name: openvpn_server
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
    - openvpn-server

- name: compilation
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 164
    root_disk_type: pd-ssd

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: us1
  vm_type: compilation
  network: concourse

networks:
- name: concourse
  type: manual
  subnets:
  - az: us1
    range: ((internal_cidr))
    gateway: ((internal_gw))
    dns: [8.8.8.8]
    reserved:
    - ((reserved_range))
    static:
    - ((static_range))
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      tags:
        - ((director_internal_tag))
- name: vip
  type: vip

disk_types:
- name: persistent
  disk_size: 500_000
  cloud_properties: {type: pd-standard}
