azs:
- name: us1
  cloud_properties: {zone: ((zone))}

vm_types:
# Used by Concourse ATC and TSA VM
- name: concourse_cpi
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
      - ((bosh_cpi.atc_tag))
      - ((nat_traffic_tag))
    target_pool: ((bosh_cpi.target_pool))
# Used by Concourse database VM
- name: concourse_cpi_database
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
      - ((bosh_cpi.db_tag))
      - ((nat_traffic_tag))
- name: concourse_core
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
      - ((bosh_core.atc_tag))
      - ((nat_traffic_tag))
    target_pool: ((bosh_core.target_pool))
- name: concourse_core_database
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    tags:
      - ((bosh_core.db_tag))
      - ((nat_traffic_tag))
# Concourse Worker vm types
- name: concourse_worker_8_24
  cloud_properties:
    cpu: 8
    ram: 24_576
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((bosh_cpi.worker_tag))
- name: concourse_worker_2_8
  cloud_properties:
    cpu: 2
    ram: 8_192
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
      - ((bosh_cpi.worker_tag))
- name: concourse_core_worker_8_16
  cloud_properties:
    cpu: 8
    ram: 16_384
    root_disk_size_gb: 164
    root_disk_type: pd-ssd
    tags:
      - ((nat_traffic_tag))
      - ((bosh_core.worker_tag))

# Used by OpenVPN Server
- name: openvpn_server
  cloud_properties:
    cpu: 1
    ram: 2_560
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
    - ((vpn_server_tag))

- name: compilation
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 164
    root_disk_type: pd-ssd

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: us1
  vm_type: compilation
  network: concourse

networks:
- name: concourse
  type: dynamic
  subnets:
  - az: us1
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      tags:
        - ((director_internal_tag))
        - ((jumpbox_internal_management_tag))
- name: vip
  type: vip

disk_types:
- name: persistent
  disk_size: 500_000
  cloud_properties: {type: pd-standard}
- name: persistent-ssd
  disk_size: 500_000
  cloud_properties: {type: pd-ssd}
