azs:
- name: us1
  cloud_properties: {zone: ((zone))}

vm_types:
- name: concourse_cpi
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
      - ((concourse_atc_tag))
      - ((nat_traffic_tag))
    target_pool: ((concourse_target_pool))
- name: concourse_cpi_database
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    tags:
      - ((concourse_db_tag))
      - ((nat_traffic_tag))
- name: concourse_cpi_worker
  cloud_properties:
    cpu: 8
    ram: 16_384
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
- name: concourse_cpi_sf_worker_small
  cloud_properties:
    cpu: 4
    ram: 16_384
    root_disk_size_gb: 164
    root_disk_type: pd-standard
    tags:
      - ((nat_traffic_tag))
- name: compilation
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 15
    root_disk_type: pd-ssd
    preemptible: true

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: us1
  vm_type: compilation
  network: concourse

networks:
  - name: concourse
    type: dynamic
    subnets:
    - az: us1
      cloud_properties:
        network_name: ((network))
        subnetwork_name: ((subnetwork))
        tags:
          - ((director_internal_tag))
  - name: vip
    type: vip

disk_types:
  - name: persistent
    disk_size: 500_000
    cloud_properties: {type: pd-standard}
