---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: deployments-src

params:
  GOOGLE_PROJECT_ID:  ""
  GOOGLE_CREDENTIALS: ""

run:
  path: deployments-src/ci/tasks/delete-firewall-rules
