---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: deployments-src
  - name: bosh-cli
  - name: worker-state
  - name: stemcell

outputs:
  - name: updated-worker-state

params:
  IAAS_CREDENTIALS:    ""

run:
  path: deployments-src/ci/tasks/deploy-worker
