---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
  - name: deployments-src
  - name: bosh-cpi-release
  - name: bosh-cli
  - name: concourse
  - name: garden-runc-release
  - name: os-conf-release
  - name: worker-state
  - name: stemcell
  - name: terraform

outputs:
  - name: updated-worker-state

params:
  GOOGLE_CREDENTIALS: ""
  ENVIRONMENT_NAME:   ""
  WORKER_SECRETS:     ""
  JUMPBOX_SSH_USER:   "jumpbox"
  JUMPBOX_SSH_KEY:    ""
  RUBY_VERSION:       "2.3.1"

run:
  path: deployments-src/ci/tasks/deploy-worker-asia
