---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: terraform
  - name: deployments-src
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: bosh-cli

outputs:
  - name: output-src

params:
  BOSH_DIRECTOR_SECRETS: ""
  BOSH_ENVIRONMENT:      ""
  BOSH_USER:             ""
  BOSH_PASSWORD:         ""

run:
  path: deployments-src/ci/tasks/deploy-director
