---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: terraform
  - name: deployments-src
  - name: bosh-cli

params:
  BOSH_USER:             ""
  BOSH_PASSWORD:         ""
  BOSH_CA_CERT:          ""
  JUMPBOX_SSH_USER:      ""
  JUMPBOX_SSH_KEY:       ""
  SUBNET_NAME:           ""

run:
  path: deployments-src/ci/tasks/update-cloud-config
