---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: deployments-src

params:
  SLEEP_TIME:   "1800"
  JUMPBOX_HOST: ""

run:
  path: deployments-src/ci/tasks/wait-for-ssh
