---
# post-install addition of CPI GitHub Team for auth, only needed for fresh install:
# fly -t upgrader set-team -n bosh-cpi --github-auth-client-id $(lpass show --username "BOSH Concourse Upgrader GitHub Auth") --github-auth-client-secret $(lpass show --password "BOSH Concourse Upgrader GitHub Auth") --github-auth-team "cloudfoundry/CF BOSH CPI"
name: concourse-cpi

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 8
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000

instance_groups:
- name: concourse_cpi
  instances: 1
  vm_type: concourse_cpi
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
      default: [dns, gateway]
  jobs:
    - name: atc
      release: concourse
      properties:
        external_url: ((concourse_external_url))
        bind_port: 80
        tls_bind_port: 443
        tls_cert: ((tls_cert))
        tls_key: ((tls_key))
        publicly_viewable: true
        postgresql_database: &atc_db atc
        github_auth:
          client_id: ((github_client_id))
          client_secret: ((github_client_secret))
          # these users will have access to the `main` team
          authorize: ((github_authorized_teams))
    - name: tsa
      release: concourse
      properties:
        host_key: ((tsa_private_key))
        host_public_key: ((tsa_public_key))
        team_authorized_keys:
        - team: ((bosh_cpi_team))
          ssh_key: ((bosh_cpi_team_ssh_public_key))
        - team: ((bosh_sap_team))
          ssh_key: ((bosh_sap_team_ssh_public_key))

- name: concourse_cpi_database
  instances: 1
  vm_type: concourse_cpi_database
  stemcell: default
  azs: [us1]
  persistent_disk_pool: persistent
  networks:
    - name: concourse
      default: [dns, gateway]
  jobs:
    - name: postgresql
      release: concourse
      properties:
        databases:
          - name: *atc_db
            role: atc
            password: ((concourse_db_password))

- name: concourse_cpi_sf_worker
  instances: 1
  vm_type: concourse_cpi_worker
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim: {from: sf_baggageclaim}
      properties:
        team: ((bosh_cpi_team))
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
    - name: garden
      release: garden-runc
      properties:
        garden:
          listen_network: tcp
          listen_address: 127.0.0.1:7777
    - name: baggageclaim
      release: concourse
      provides:
        baggageclaim: {as: sf_baggageclaim}
      properties: {}

- name: concourse_cpi_sap_worker
  instances: 1
  vm_type: concourse_cpi_worker
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim: {from: sap_baggageclaim}
      properties:
        team: ((bosh_sap_team))
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
    - name: garden
      release: garden-runc
      properties:
        garden:
          listen_network: tcp
          listen_address: 127.0.0.1:7777
    - name: baggageclaim
      release: concourse
      provides:
        baggageclaim: {as: sap_baggageclaim}
      properties: {}

# - name: concourse_cpi_sf_worker_asia
#   instances: 1
#   vm_type: concourse_cpi_sf_worker_small
#   stemcell: default
#   azs: [asia1]
#   networks:
#     - name: concourse
#   jobs:
#     - name: groundcrew
#       release: concourse
#       consumes:
#         baggageclaim: {from: asia_baggageclaim}
#       properties:
#         tags: [asia]
#         team: ((bosh_cpi_team))
#         baggageclaim:
#           forward_address: 127.0.0.1:7788
#         garden:
#           forward_address: 127.0.0.1:7777
#     - name: garden
#       release: garden-runc
#       properties:
#         garden:
#           listen_network: tcp
#           listen_address: 127.0.0.1:7777
#     - name: baggageclaim
#       release: concourse
#       provides:
#         baggageclaim: {as: asia_baggageclaim}
#       properties: {}
