---
# post-install addition of CPI GitHub Team for auth, only needed for fresh install:
# fly -t upgrader set-team -n bosh-cpi --github-auth-client-id $(lpass show --username "BOSH Concourse Upgrader GitHub Auth") --github-auth-client-secret $(lpass show --password "BOSH Concourse Upgrader GitHub Auth") --github-auth-team "cloudfoundry/CF BOSH CPI"
name: concourse-cpi

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 8
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000

instance_groups:
- name: concourse_cpi
  instances: 1
  vm_type: concourse_cpi
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
      default: [dns, gateway]
  jobs:
    - name: atc
      release: concourse
      properties:
        external_url: ((concourse_external_url))
        bind_port: 80
        tls_bind_port: 443
        tls_cert: ((tls_cert))
        tls_key: ((tls_key))
        publicly_viewable: true
        postgresql_database: &atc_db atc
        basic_auth_username: ((concourse_basic_auth_username))
        basic_auth_password: ((concourse_basic_auth_password))
    - name: tsa
      release: concourse
      properties:
        host_key: ((tsa_private_key))
        host_public_key: ((tsa_public_key))
        team_authorized_keys:
        - team: ((bosh_cpi_team))
          ssh_key: ((bosh_cpi_team_ssh_public_key))
        - team: ((bosh_sap_team))
          ssh_key: ((bosh_sap_team_ssh_public_key))

- name: concourse_cpi_database
  instances: 1
  vm_type: concourse_cpi_database
  stemcell: default
  azs: [us1]
  persistent_disk_pool: persistent
  networks:
    - name: concourse
      default: [dns, gateway]
  jobs:
    - name: postgresql
      release: concourse
      properties:
        databases:
          - name: *atc_db
            role: atc
            password: ((concourse_db_password))

# worker instances will be added via ops file
