---
# post-install addition of CPI GitHub Team for auth, only needed for fresh install:
# fly -t upgrader set-team -n bosh-cpi --github-auth-client-id $(lpass show --username "BOSH Concourse Upgrader GitHub Auth") --github-auth-client-secret $(lpass show --password "BOSH Concourse Upgrader GitHub Auth") --github-auth-team "cloudfoundry/CF BOSH CPI"
name: concourse-cpi

releases:
- name: concourse
  version: ((concourse_version))
- name: garden-runc
  version: ((garden_version))
- name: ulimit
  version: latest
- name: postgres
  version: ((postgres_version))

stemcells:
- alias: default
  os: ubuntu-trusty
  version: ((stemcell_version))

update:
  serial: false
  canaries: 100
  max_in_flight: 100
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000

instance_groups:
- name: concourse_cpi
  instances: 1
  vm_type: concourse_cpi
  stemcell: default
  azs: [us1]
  networks:
  - name: concourse
    default: [dns, gateway]
  jobs:
    - name: atc
      release: concourse
      properties:
        external_url: ((concourse_external_url))
        bind_port: 80
        tls_bind_port: 443
        tls_cert: ((tls_cert))
        tls_key: ((tls_key))
        publicly_viewable: true
        postgresql:
          database: &atc_db atc
          role:
            name: atc
            password: ((concourse_db_password))
        basic_auth_username: ((concourse_basic_auth_username))
        basic_auth_password: ((concourse_basic_auth_password))
        token_signing_key: ((token_signing_key))
    - name: tsa
      release: concourse
      properties:
        host_key: ((tsa_host_key))
        token_signing_key: ((token_signing_key))
        authorized_keys: [((worker_key.public_key))]
        team_authorized_keys: [] # keys will be added via worker-ops.yml
    - name: ulimit
      release: ulimit
      properties:
        nofile:
          soft: 32768
          hard: 32768

- name: concourse_cpi_database
  instances: 1
  vm_type: concourse_cpi_database
  stemcell: default
  azs: [us1]
  persistent_disk_pool: persistent-ssd
  networks:
    - name: concourse
      default: [dns, gateway]
  jobs:
    - name: postgres
      release: postgres
      properties:
        databases:
          port: 5432
          databases:
            - name: *atc_db
          roles:
            - name: atc
              password: ((concourse_db_password))

- name: shared_worker
  instances: 3
  vm_type: concourse_worker_8_24
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim: {from: shared_baggageclaim}
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
    - name: garden
      release: garden-runc
      properties:
        garden:
          max_containers: 500
          listen_network: tcp
          listen_address: 127.0.0.1:7777
    - name: baggageclaim
      release: concourse
      provides:
        baggageclaim: {as: shared_baggageclaim}
      properties: {}

# worker instances will be added via worker-ops.yml
