---
jobs:
  - name: update-natbox
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
          - get: us-natbox-state
          - get: asia-natbox-state
          - get: bosh-google-cpi-release
          - get: networking-release
          - get: stemcell
        - put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/
            vars:
              allow_mbus_access_to_natbox: 1
        - task: update-us-natbox
          file: deployments-src/ci/tasks/deploy-natbox.yml
          params:
            GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
            NATBOX_SECRETS:     {{natbox_secrets}}
            REGION:             us
          input_mapping:
            natbox-state: us-natbox-state
          ensure:
            put: us-natbox-state
            params:
              file: updated-natbox-state/us-natbox-state.json
        - task: update-asia-natbox
          file: deployments-src/ci/tasks/deploy-natbox.yml
          params:
            GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
            NATBOX_SECRETS:     {{natbox_secrets}}
            REGION:             asia
          input_mapping:
            natbox-state: asia-natbox-state
          ensure:
            put: asia-natbox-state
            params:
              file: updated-natbox-state/asia-natbox-state.json
        ensure:
          put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/
            vars:
              allow_mbus_access_to_natbox: 0

  - name: update-jumpbox
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
          - get: jumpbox-state
          - get: jumpbox-deployment-src
        - put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/
            vars:
              allow_mbus_access_to_jumpbox: 1
        - task: update-jumpbox
          file: deployments-src/ci/tasks/deploy-jumpbox.yml
          params:
            GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
            JUMPBOX_SECRETS:    {{jumpbox_secrets}}
          ensure:
            put: jumpbox-state
            params:
              file: updated-jumpbox-state/jumpbox-state.json
            ensure:
              put: terraform
              params:
                env_name: bosh-cpi-concourse
                terraform_source: deployments-src/terraform/
                vars:
                  allow_mbus_access_to_jumpbox: 0

  - name: update-director
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: director-templates
          - get: bosh-cli
          - get: director-state
        - &open-ssh-to-jumpbox
          put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/
            vars:
              allow_ssh_access_to_jumpbox: 1
        - task: update-director
          file: deployments-src/ci/tasks/deploy-director.yml
          params:
            GOOGLE_CREDENTIALS:      {{gcp_credentials_json}}
            BOSH_DIRECTOR_SECRETS:   {{bosh_director_secrets}}
            BOSH_USER:               {{director_admin_username}}
            BOSH_PASSWORD:           {{director_admin_password}}
            BOSH_CA_CERT:            {{director_ca_cert}}
            BOSH_CA_KEY:             {{director_ca_key}}
            JUMPBOX_SSH_KEY:         {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:        {{jumpbox_ssh_user}}
          ensure:
            put: director-state
            params:
              file: updated-director-state/bosh-state.json
            ensure: &close-ssh-to-jumpbox
              put: terraform
              params:
                env_name: bosh-cpi-concourse
                terraform_source: deployments-src/terraform/
                vars:
                  allow_ssh_access_to_jumpbox: 0

  - name: update-cloud-config
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
        - *open-ssh-to-jumpbox
        - task: update-cloud-config
          file: deployments-src/ci/tasks/update-cloud-config.yml
          params:
            BOSH_USER:             {{director_admin_username}}
            BOSH_PASSWORD:         {{director_admin_password}}
            BOSH_CA_CERT:          {{director_ca_cert}}
            JUMPBOX_SSH_KEY:       {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:      {{jumpbox_ssh_user}}
          ensure: *close-ssh-to-jumpbox

  - name: update-concourse
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: stemcell
          - get: bosh-cli
          - get: concourse-and-garden
            params:
              globs: ['concourse-*.tgz','garden-runc-*.tgz']
        - *open-ssh-to-jumpbox
        - task: deploy-concourse
          file: deployments-src/ci/tasks/deploy-concourse.yml
          params:
            DEPLOYMENT_NAME:        concourse-cpi
            DEPLOYMENT_CONFIG_PATH: concourse/concourse-cpi.yml
            CONCOURSE_SECRETS:      {{concourse_secrets}}
            BOSH_USER:              {{director_admin_username}}
            BOSH_PASSWORD:          {{director_admin_password}}
            BOSH_CA_CERT:           {{director_ca_cert}}
            JUMPBOX_SSH_KEY:        {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:       {{jumpbox_ssh_user}}
          ensure: *close-ssh-to-jumpbox

  - name: open-ssh-for-30m
    serial_groups: [deploy]
    plan:
      - do:
        - get: deployments-src
        - *open-ssh-to-jumpbox
        - task: wait-for-ssh
          file: deployments-src/ci/tasks/wait-for-ssh.yml
          ensure: *close-ssh-to-jumpbox

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
  - name: gcs-resource
    type: docker-image
    source:
      # TODO: change back after PR is merged: https://github.com/frodenas/gcs-resource/pull/4
      # repository: frodenas/gcs-resource
      repository: boshcpi/gcs-resource
      tag: PR-fix-versioned-put

resources:
  - name: deployments-src
    type: git
    source:
      uri: https://github.com/pivotal-cf/bosh-concourse-deployments.git
      # branch: master
      branch: WIP-add-terraform-templates
  - name: director-templates
    type: git
    source:
      uri: https://github.com/ljfranklin/bosh-deployment.git
      # branch: master
      branch: PR-cpi-team-feedback
  - name: jumpbox-deployment-src
    type: git
    source:
      uri: https://github.com/ljfranklin/jumpbox-deployment.git
      # branch: master
      branch: PR-cpi-team-feedback
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{deployments_bucket_name}}
        bucket_path: terraform/
        access_key_id: {{storage_access_key}}
        secret_access_key: {{storage_secret_key}}
        endpoint: https://storage.googleapis.com
      vars:
        project_id: {{project_id}}
        gcp_credentials_json: {{gcp_credentials_json}}
        trusted_cidr: {{trusted_cidr}}
  - name: us-natbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: natbox/us-natbox-state.json
  - name: asia-natbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: natbox/asia-natbox-state.json
  - name: jumpbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: jumpbox/jumpbox-state.json
  - name: director-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: director/bosh-state.json
  - name: bosh-cli
    type: s3
    source:
      bucket: bosh-cli-artifacts
      regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
  - name: bosh-google-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-google-cpi-release
  - name: networking-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/networking-release
  - name: concourse-and-garden
    type: github-release
    source:
      repository: concourse
      user: concourse
      access_token: {{concourse-config-access-token}}
