---
jobs:
  - name: update-google-asia-worker
    serial_groups: [deploy-asia] # ensure Terraform state files don't get clobbered
    plan:
      - do:
        - aggregate:
          - get: concourse-update-trigger # this file is updated by concourse-cpi pipeline
            trigger: true
          - get: deployments-src
          - get: bosh-cli
          - get: worker-state
            resource: google-asia-worker-state
          - get: bosh-cpi-release
            resource: bosh-google-cpi-release
          - get: concourse-and-garden
            params:
              globs: ['concourse-*.tgz','garden-runc-*.tgz']
          - get: stemcell
        - &asia-open-ssh-to-jumpbox
          put: terraform
          params:
            env_name: bosh-cpi-concourse-asia
            terraform_source: deployments-src/terraform/asia
            vars:
              allow_ssh_access_to_jumpbox: 1
        - aggregate:
          - task: update-google-asia-worker
            file: deployments-src/ci/tasks/deploy-worker-asia.yml
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              WORKER_SECRETS:     {{google-asia-worker-secrets}}
              ENVIRONMENT_NAME:   google-asia-worker
              JUMPBOX_SSH_KEY:    {{jumpbox_ssh_key}}
            ensure:
              put: worker-state
              resource: google-asia-worker-state
              params:
                file: updated-worker-state/worker-state.json
              ensure: &asia-close-ssh-to-jumpbox
                put: terraform
                params:
                  env_name: bosh-cpi-concourse-asia
                  terraform_source: deployments-src/terraform/asia
                  vars:
                    allow_ssh_access_to_jumpbox: 0

  - name: update-vsphere-v6.0-worker
    plan:
      - do:
        - aggregate:
          - get: concourse-update-trigger
            trigger: true
          - get: deployments-src
          - get: bosh-cli
          - get: worker-state
            resource: vsphere-v6.0-worker-state
          - get: bosh-cpi-release
            resource: bosh-vsphere-cpi-release
          - get: concourse-and-garden
            params:
              globs: ['concourse-*.tgz','garden-runc-*.tgz']
          - get: stemcell
            resource: vsphere-stemcell
        - aggregate:
          - task: update-vsphere-v6.0-worker
            file: deployments-src/ci/tasks/deploy-worker.yml
            params:
              WORKER_SECRETS: {{vsphere-v60-worker-secrets}}
              ENVIRONMENT_NAME: vsphere-v6.0
            ensure:
              put: worker-state
              resource: vsphere-v6.0-worker-state
              params:
                file: updated-worker-state/worker-state.json

  - name: prepare-asia-env
    serial_groups: [deploy-asia]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: jumpbox-deployment-src
          - get: bosh-cli
          - get: asia-natbox-state
          - get: asia-jumpbox-state
          - get: bosh-google-cpi-release
          - get: networking-release
          - get: stemcell
        - put: terraform
          params:
            env_name: bosh-cpi-concourse-asia
            terraform_source: deployments-src/terraform/asia
            vars:
              allow_mbus_access_to_natbox: 1
              allow_mbus_access_to_jumpbox: 1
        - aggregate:
          - task: update-natbox
            file: deployments-src/ci/tasks/deploy-natbox.yml
            input_mapping:
              natbox-state: asia-natbox-state
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              NATBOX_SECRETS:     {{natbox_secrets}}
            ensure:
              put: asia-natbox-state
              params:
                file: updated-natbox-state/natbox-state.json
          - task: update-jumpbox
            file: deployments-src/ci/tasks/deploy-jumpbox.yml
            input_mapping:
              jumpbox-state: asia-jumpbox-state
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              JUMPBOX_SECRETS:    {{jumpbox_secrets}}
              JUMPBOX_PUBLIC_KEY: {{jumpbox_public_key}}
              TRUSTED_CIDRS:      {{trusted_cidrs}}
              MACHINE_TYPE:       {{jumpbox_machine_type}}
            ensure:
              put: asia-jumpbox-state
              params:
                file: updated-jumpbox-state/jumpbox-state.json
        ensure:
          put: terraform
          params:
            env_name: bosh-cpi-concourse-asia
            terraform_source: deployments-src/terraform/asia
            vars:
              allow_mbus_access_to_natbox: 0
              allow_mbus_access_to_jumpbox: 0


  - name: open-ssh-for-30m
    serial_groups: [deploy-asia]
    plan:
      - do:
        - get: deployments-src
        - *asia-open-ssh-to-jumpbox
        - task: wait-for-ssh
          file: deployments-src/ci/tasks/wait-for-ssh.yml
        ensure: *asia-close-ssh-to-jumpbox

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: deployments-src
    type: git
    source:
      uri: https://github.com/pivotal-cf/bosh-concourse-deployments.git
      branch: master
  - name: jumpbox-deployment-src
    type: git
    source:
      uri: https://github.com/cppforlife/jumpbox-deployment.git
      branch: master
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{deployments_bucket_name}}
        bucket_path: terraform/
        access_key_id: {{storage_access_key}}
        secret_access_key: {{storage_secret_key}}
        endpoint: https://storage.googleapis.com
      vars:
        project_id: {{project_id}}
        gcp_credentials_json: {{gcp_credentials_json}}
        trusted_cidrs: {{trusted_cidrs}}
  - name: asia-natbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: asia/natbox-state.json
  - name: asia-jumpbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: asia/jumpbox-state.json
  - name: vsphere-v6.0-worker-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: worker/vsphere-v6.0-worker-state.json
  - name: google-asia-worker-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: worker/google-asia-worker-state.json
  - name: concourse-update-trigger
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: concourse/concourse-update-trigger
  - name: bosh-cli
    type: s3
    source:
      bucket: bosh-cli-artifacts
      regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
  - name: vsphere-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  - name: bosh-google-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-google-cpi-release
  - name: bosh-vsphere-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vsphere-cpi-release
  - name: networking-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/networking-release
  - name: concourse-and-garden
    type: github-release
    source:
      repository: concourse
      user: concourse
      access_token: {{concourse_config_access_token}}
