---
jobs:
  - name: prepare-asia-env
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: jumpbox-deployment-src
          - get: bosh-cli
          - get: asia-natbox-state
          - get: asia-jumpbox-state
          - get: bosh-google-cpi-release
          - get: networking-release
          - get: stemcell
        - put: terraform
          params:
            env_name: bosh-cpi-concourse-asia
            terraform_source: deployments-src/terraform/asia
            vars:
              allow_mbus_access_to_natbox: 1
              allow_mbus_access_to_jumpbox: 1
        - aggregate:
          - task: update-natbox
            file: deployments-src/ci/tasks/deploy-natbox.yml
            input_mapping:
              natbox-state: asia-natbox-state
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              NATBOX_SECRETS:     {{natbox_secrets}}
            ensure:
              put: asia-natbox-state
              params:
                file: updated-natbox-state/natbox-state.json
          - task: update-jumpbox
            file: deployments-src/ci/tasks/deploy-jumpbox.yml
            input_mapping:
              jumpbox-state: asia-jumpbox-state
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              JUMPBOX_SECRETS:    {{jumpbox_secrets}}
            ensure:
              put: asia-jumpbox-state
              params:
                file: updated-jumpbox-state/jumpbox-state.json
        ensure:
          put: terraform
          params:
            env_name: bosh-cpi-concourse-asia
            terraform_source: deployments-src/terraform/asia
            vars:
              allow_mbus_access_to_natbox: 0
              allow_mbus_access_to_jumpbox: 0

  - name: prepare-concourse-env
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: jumpbox-deployment-src
          - get: bosh-cli
          - get: concourse-natbox-state
          - get: concourse-jumpbox-state
          - get: bosh-google-cpi-release
          - get: networking-release
          - get: stemcell
        - put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/concourse
            vars:
              allow_mbus_access_to_natbox: 1
              allow_mbus_access_to_jumpbox: 1
        - aggregate:
          - task: update-natbox
            file: deployments-src/ci/tasks/deploy-natbox.yml
            input_mapping:
              natbox-state: concourse-natbox-state
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              NATBOX_SECRETS:     {{natbox_secrets}}
            ensure:
              put: concourse-natbox-state
              params:
                file: updated-natbox-state/natbox-state.json
          - task: update-jumpbox
            file: deployments-src/ci/tasks/deploy-jumpbox.yml
            input_mapping:
              jumpbox-state: concourse-jumpbox-state
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              JUMPBOX_SECRETS:    {{jumpbox_secrets}}
            ensure:
              put: concourse-jumpbox-state
              params:
                file: updated-jumpbox-state/jumpbox-state.json
        ensure:
          put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/concourse
            vars:
              allow_mbus_access_to_natbox: 0
              allow_mbus_access_to_jumpbox: 0

  - name: update-director
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: director-templates
          - get: bosh-cli
          - get: director-state
        - &open-ssh-to-jumpbox
          put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/concourse
            vars:
              allow_ssh_access_to_jumpbox: 1
        - task: update-director
          file: deployments-src/ci/tasks/deploy-director.yml
          params:
            GOOGLE_CREDENTIALS:      {{gcp_credentials_json}}
            BOSH_DIRECTOR_SECRETS:   {{bosh_director_secrets}}
            BOSH_CLIENT:             {{director_admin_username}}
            BOSH_CLIENT_SECRET:      {{director_admin_password}}
            BOSH_CA_CERT:            {{director_ca_cert}}
            BOSH_CA_KEY:             {{director_ca_key}}
            JUMPBOX_SSH_KEY:         {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:        {{jumpbox_ssh_user}}
          ensure:
            put: director-state
            params:
              file: updated-director-state/bosh-state.json
            ensure: &close-ssh-to-jumpbox
              put: terraform
              params:
                env_name: bosh-cpi-concourse
                terraform_source: deployments-src/terraform/concourse
                vars:
                  allow_ssh_access_to_jumpbox: 0

  - name: update-cloud-config
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
        - *open-ssh-to-jumpbox
        - task: update-cloud-config
          file: deployments-src/ci/tasks/update-cloud-config.yml
          params:
            BOSH_CLIENT:           {{director_admin_username}}
            BOSH_CLIENT_SECRET:    {{director_admin_password}}
            BOSH_CA_CERT:          {{director_ca_cert}}
            JUMPBOX_SSH_KEY:       {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:      {{jumpbox_ssh_user}}
          ensure: *close-ssh-to-jumpbox

  - name: update-concourse
    serial_groups: [deploy]
    plan:
      - do:
          - aggregate:
            - get: deployments-src
            - get: stemcell
            - get: bosh-cli
            - get: concourse-and-garden
              params:
                globs: ['concourse-*.tgz','garden-runc-*.tgz']
          - *open-ssh-to-jumpbox
          - task: deploy-concourse
            file: deployments-src/ci/tasks/deploy-concourse.yml
            params:
              DEPLOYMENT_NAME:               concourse-cpi
              DEPLOYMENT_CONFIG_PATH:        concourse/concourse-cpi.yml
              CONCOURSE_SECRETS:             {{concourse_secrets}}
              BOSH_CLIENT:                   {{director_admin_username}}
              BOSH_CLIENT_SECRET:            {{director_admin_password}}
              BOSH_CA_CERT:                  {{director_ca_cert}}
              JUMPBOX_SSH_KEY:               {{jumpbox_ssh_key}}
              JUMPBOX_SSH_USER:              {{jumpbox_ssh_user}}
              CONCOURSE_EXTERNAL_URL:        {{concourse_external_url}}
              CONCOURSE_BASIC_AUTH_USERNAME: {{concourse_basic_auth_username}}
              CONCOURSE_BASIC_AUTH_PASSWORD: {{concourse_basic_auth_password}}
          - task: set-teams
            file: deployments-src/ci/tasks/set-teams.yml
            params:
              CONCOURSE_EXTERNAL_URL:         {{concourse_external_url}}
              CONCOURSE_BASIC_AUTH_USERNAME:  {{concourse_basic_auth_username}}
              CONCOURSE_BASIC_AUTH_PASSWORD:  {{concourse_basic_auth_password}}
              CONCOURSE_GITHUB_CLIENT_ID:     {{concourse_github_client_id}}
              CONCOURSE_GITHUB_CLIENT_SECRET: {{concourse_github_client_secret}}
              CONCOURSE_TEAMS:                {{concourse_teams}}
        ensure: *close-ssh-to-jumpbox

  - name: update-vsphere-v5.1-worker
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
          - get: worker-state
            resource: vsphere-v5.1-worker-state
          - get: bosh-cpi-release
            resource: bosh-vsphere-cpi-release
          - get: concourse-and-garden
            passed: [update-concourse]
            trigger: true
            params:
              globs: ['concourse-*.tgz','garden-runc-*.tgz']
          - get: stemcell
            resource: vsphere-stemcell
        - aggregate:
          - task: update-vsphere-v5.1-worker
            file: deployments-src/ci/tasks/deploy-worker.yml
            params:
              WORKER_SECRETS: {{vsphere-v51-worker-secrets}}
              ENVIRONMENT_NAME: vsphere-v5.1
            ensure:
              put: worker-state
              resource: vsphere-v5.1-worker-state
              params:
                file: updated-worker-state/worker-state.json

  - name: update-vcloud-v5.5-worker
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
          - get: worker-state
            resource: vcloud-v5.5-worker-state
          - get: bosh-cpi-release
            resource: bosh-vcloud-cpi-release
          - get: concourse-and-garden
            passed: [update-concourse]
            trigger: true
            params:
              globs: ['concourse-*.tgz','garden-runc-*.tgz']
          - get: stemcell
            resource: vcloud-stemcell
        - aggregate:
          - task: update-vcloud-v5.5-worker
            file: deployments-src/ci/tasks/deploy-worker.yml
            params:
              WORKER_SECRETS: {{vcloud-v55-worker-secrets}}
              ENVIRONMENT_NAME: vcloud-v5.5
            ensure:
              put: worker-state
              resource: vcloud-v5.5-worker-state
              params:
                file: updated-worker-state/worker-state.json

  - name: update-google-asia-worker
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
          - get: worker-state
            resource: google-asia-worker-state
          - get: bosh-cpi-release
            resource: bosh-google-cpi-release
          - get: concourse-and-garden
            passed: [update-concourse]
            trigger: true
            params:
              globs: ['concourse-*.tgz','garden-runc-*.tgz']
          - get: stemcell
        - &asia-open-ssh-to-jumpbox
          put: terraform
          params:
            env_name: bosh-cpi-concourse-asia
            terraform_source: deployments-src/terraform/asia
            vars:
              allow_ssh_access_to_jumpbox: 1
        - aggregate:
          - task: update-google-asia-worker
            file: deployments-src/ci/tasks/deploy-worker-asia.yml
            params:
              GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
              WORKER_SECRETS: {{google-asia-worker-secrets}}
              ENVIRONMENT_NAME: google-asia-worker
              JUMPBOX_SSH_KEY:        {{jumpbox_ssh_key}}
              JUMPBOX_SSH_USER:       {{jumpbox_ssh_user}}
            ensure:
              put: worker-state
              resource: google-asia-worker-state
              params:
                file: updated-worker-state/worker-state.json
              ensure: &asia-close-ssh-to-jumpbox
                put: terraform
                params:
                  env_name: bosh-cpi-concourse-asia
                  terraform_source: deployments-src/terraform/asia
                  vars:
                    allow_ssh_access_to_jumpbox: 0

  - name: open-ssh-for-30m
    serial_groups: [deploy]
    plan:
      - do:
        - get: deployments-src
        - aggregate:
          - *open-ssh-to-jumpbox
          - *asia-open-ssh-to-jumpbox
        - task: wait-for-ssh
          file: deployments-src/ci/tasks/wait-for-ssh.yml
          ensure:
            aggregate:
              - *close-ssh-to-jumpbox
              - *asia-close-ssh-to-jumpbox

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: 0.8.1
  - name: gcs-resource
    type: docker-image
    source:
      # TODO: change back after PR is merged: https://github.com/frodenas/gcs-resource/pull/4
      # repository: frodenas/gcs-resource
      repository: boshcpi/gcs-resource
      tag: PR-fix-versioned-put

resources:
  - name: deployments-src
    type: git
    source:
      uri: https://github.com/pivotal-cf/bosh-concourse-deployments.git
      # branch: master
      branch: WIP-add-terraform-templates
  - name: director-templates
    type: git
    source:
      uri: https://github.com/ljfranklin/bosh-deployment.git
      # branch: master
      branch: PR-cpi-team-feedback
  - name: jumpbox-deployment-src
    type: git
    source:
      uri: https://github.com/ljfranklin/jumpbox-deployment.git
      # branch: master
      branch: PR-cpi-team-feedback
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{deployments_bucket_name}}
        bucket_path: terraform/
        access_key_id: {{storage_access_key}}
        secret_access_key: {{storage_secret_key}}
        endpoint: https://storage.googleapis.com
      vars:
        project_id: {{project_id}}
        gcp_credentials_json: {{gcp_credentials_json}}
        trusted_cidr: {{trusted_cidr}}
  - name: concourse-natbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: concourse/natbox-state.json
  - name: concourse-jumpbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: concourse/jumpbox-state.json
  - name: asia-natbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: asia/natbox-state.json
  - name: asia-jumpbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: asia/jumpbox-state.json
  - name: vsphere-v5.1-worker-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: worker/vsphere-v5.1-worker-state.json
  - name: vcloud-v5.5-worker-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: worker/vcloud-v5.5-worker-state.json
  - name: google-asia-worker-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: worker/google-asia-worker-state.json
  - name: director-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: director/bosh-state.json
  - name: bosh-cli
    type: s3
    source:
      bucket: bosh-cli-artifacts
      regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
  - name: vsphere-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  - name: vcloud-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
  - name: bosh-google-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-google-cpi-release
  - name: bosh-vsphere-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vsphere-cpi-release
  - name: bosh-vcloud-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vcloud-cpi-release
  - name: networking-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/networking-release
  - name: concourse-and-garden
    type: github-release
    source:
      repository: concourse
      user: concourse
      access_token: {{concourse-config-access-token}}
