---
jobs:
  - name: update-director
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: director-templates
          - get: bosh-cli
          - get: director-state
        - put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/
            vars:
              allow_director_access_via_jumpbox: 1
        - task: update-director
          file: deployments-src/ci/tasks/deploy-director.yml
          params:
            GOOGLE_CREDENTIALS_JSON: {{google_credentials_json}}
            BOSH_DIRECTOR_SECRETS:   {{bosh_director_secrets}}
            BOSH_ENVIRONMENT:        {{director_url}}
            BOSH_USER:               {{director_admin_username}}
            BOSH_PASSWORD:           {{director_admin_password}}
            DEFAULT_CA_JSON:         {{default_ca_json}}
            JUMPBOX_SSH_KEY:         {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:        {{jumpbox_ssh_user}}
          ensure:
            put: director-state
            params:
              file: updated-director-state/bosh-state.json
            ensure:
              put: terraform
              params:
                env_name: bosh-cpi-concourse
                terraform_source: deployments-src/terraform/
                vars:
                  allow_director_access_via_jumpbox: 0

  - name: update-cloud-config
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
        - put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/
        - task: update-cloud-config
          file: deployments-src/ci/tasks/update-cloud-config.yml
          params:
            BOSH_ENVIRONMENT:      {{director_url}}
            BOSH_USER:             {{director_admin_username}}
            BOSH_PASSWORD:         {{director_admin_password}}

  - name: update-concourse
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: stemcell
          - get: bosh-cli
          - get: concourse-and-garden
            params:
              globs: ['concourse-*.tgz','garden-runc-*.tgz']
        - put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/
        - task: deploy-concourse
          file: deployments-src/ci/tasks/deploy-concourse.yml
          params:
            DEPLOYMENT_NAME:        concourse-cpi
            DEPLOYMENT_CONFIG_PATH: concourse/concourse-cpi.yml
            CONCOURSE_SECRETS:      {{concourse_secrets}}
            BOSH_ENVIRONMENT:       {{director_url}}
            BOSH_USER:              {{director_admin_username}}
            BOSH_PASSWORD:          {{director_admin_password}}

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
  - name: gcs-resource
    type: docker-image
    source:
      # TODO: change back after PR is merged: https://github.com/frodenas/gcs-resource/pull/4
      # repository: frodenas/gcs-resource
      repository: boshcpi/gcs-resource
      tag: PR-fix-versioned-put

resources:
  - name: deployments-src
    type: git
    source:
      uri: git@github.com:pivotal-cf/bosh-concourse-deployments.git
      private_key: {{deployments_github_deploy_key}}
      # branch: master
      branch: WIP-add-terraform-templates
  - name: director-templates
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      # branch: master
      branch: PR-cpi-team-feedback
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{deployments_bucket_name}}
        bucket_path: terraform/
        access_key_id: {{storage_access_key}}
        secret_access_key: {{storage_secret_key}}
        endpoint: https://storage.googleapis.com
      vars:
        google_project_id: {{google_project_id}}
        google_credentials_json: {{google_credentials_json}}
        trusted_cidr: {{trusted_cidr}}
  - name: director-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{google_credentials_json}}
      versioned_file: director/bosh-state.json
  - name: bosh-cli
    type: s3
    source:
      bucket: bosh-cli-artifacts
      regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
  - name: concourse-and-garden
    type: github-release
    source:
      repository: concourse
      user: concourse
      access_token: {{concourse-config-access-token}}
